import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { Ops, CandidateQueue } from "./ops";
import type { SubAgents } from "./subagents";
import type { Logger } from "../util/logger";

export interface McpServerDeps {
  ops: Ops;
  subagents: SubAgents;
  candidates: CandidateQueue;
  logger: Logger;
}

export function buildMcpServer(deps: McpServerDeps): McpServer {
  const server = new McpServer({
    name: "trading-agents",
    version: "0.1.0",
  });

  const ok = (x: unknown) => ({ content: [{ type: "text" as const, text: JSON.stringify(x) }] });

  server.registerTool(
    "get_portfolio_summary",
    {
      description: "Return current equity, free quote balance, open positions, and unrealized PnL.",
      inputSchema: {},
    },
    async () => ok(await deps.ops.getPortfolioSummary()),
  );

  server.registerTool(
    "get_positions",
    {
      description: "List currently open positions with entry, stop, unrealized PnL.",
      inputSchema: {},
    },
    async () => ok(deps.ops.getPositions()),
  );

  server.registerTool(
    "get_ticker",
    {
      description: "Get best bid / ask / last price for a symbol on Binance.",
      inputSchema: { symbol: z.string() },
    },
    async ({ symbol }) => ok(await deps.ops.getTicker(symbol)),
  );

  server.registerTool(
    "get_klines",
    {
      description: "Fetch recent OHLCV candles for a symbol.",
      inputSchema: {
        symbol: z.string(),
        timeframe: z.enum(["1m", "5m", "15m", "1h", "4h", "1d"]),
        limit: z.number().int().min(10).max(500).optional(),
      },
    },
    async ({ symbol, timeframe, limit }) => ok(await deps.ops.getKlines(symbol, timeframe, limit)),
  );

  server.registerTool(
    "get_indicators",
    {
      description: "Compute EMA9, EMA21, EMA50, RSI14, ATR14 and lastClose for a symbol+timeframe.",
      inputSchema: {
        symbol: z.string(),
        timeframe: z.enum(["1m", "5m", "15m", "1h"]),
      },
    },
    async ({ symbol, timeframe }) => ok(await deps.ops.getIndicators(symbol, timeframe)),
  );

  server.registerTool(
    "check_risk_limits",
    {
      description:
        "Code-level risk check. Returns approved sizeBase/sizeQuote + stopPrice + takeProfitPrice, or rejection with a reason. LLMs cannot override this.",
      inputSchema: {
        symbol: z.string(),
        side: z.enum(["buy", "sell"]),
        desiredNotionalQuote: z.number().positive(),
      },
    },
    async ({ symbol, side, desiredNotionalQuote }) =>
      ok(await deps.ops.checkRiskLimits(symbol, side, desiredNotionalQuote)),
  );

  server.registerTool(
    "place_order",
    {
      description:
        "Place an order on Binance. In dry-run, returns a simulated filled order. Must pass candidateId for journaling.",
      inputSchema: {
        symbol: z.string(),
        side: z.enum(["buy", "sell"]),
        type: z.enum(["market", "limit", "stop_market", "stop_limit"]),
        amount: z.number().positive(),
        price: z.number().positive().optional(),
        stopPrice: z.number().positive().optional(),
        candidateId: z.string(),
      },
    },
    async (input) => ok(await deps.ops.placeOrder(input)),
  );

  server.registerTool(
    "cancel_order",
    {
      description: "Cancel an open order by id.",
      inputSchema: {
        orderId: z.string(),
        symbol: z.string(),
      },
    },
    async ({ orderId, symbol }) => ok(await deps.ops.cancelOrder(orderId, symbol)),
  );

  server.registerTool(
    "get_next_candidate",
    {
      description:
        "Long-poll for the next signal candidate generated by code. Blocks up to timeoutMs (default 25000). Returns the candidate object, or null if no candidate arrived in time. PM should call this when it has no other work, to stay attentive to new signals.",
      inputSchema: {
        timeoutMs: z.number().int().min(100).max(55_000).optional(),
      },
    },
    async ({ timeoutMs }) => ok(await deps.candidates.next(timeoutMs ?? 25_000)),
  );

  server.registerTool(
    "delegate_to_risk",
    {
      description:
        "Delegate a sizing / risk-limit decision to the Risk agent. Provide the candidate or a description of the proposed trade. Returns the Risk agent's JSON decision.",
      inputSchema: {
        task: z.string(),
        context: z.record(z.unknown()).optional(),
      },
    },
    async ({ task, context }) => {
      const text = await deps.subagents.delegateToRisk(task, context);
      return ok({ text });
    },
  );

  server.registerTool(
    "delegate_to_strategy",
    {
      description:
        "Delegate qualitative judgment on a candidate to the Strategy agent. Returns the Strategy agent's JSON verdict (takeIt + confidence + reasoning).",
      inputSchema: {
        task: z.string(),
        context: z.record(z.unknown()).optional(),
      },
    },
    async ({ task, context }) => {
      const text = await deps.subagents.delegateToStrategy(task, context);
      return ok({ text });
    },
  );

  server.registerTool(
    "delegate_to_execution",
    {
      description:
        "Delegate order placement to the Execution agent. Pass the risk-approved size, stop, take-profit, and candidateId. Returns the Execution agent's JSON receipt.",
      inputSchema: {
        task: z.string(),
        context: z.record(z.unknown()).optional(),
      },
    },
    async ({ task, context }) => {
      const text = await deps.subagents.delegateToExecution(task, context);
      return ok({ text });
    },
  );

  return server;
}
