import Anthropic from "@anthropic-ai/sdk";
import type { Ops } from "./ops";
import type { Logger } from "../util/logger";

const RISK_SYSTEM = `You are the Risk / PnL agent.

Given a proposed trade (symbol, side, desired notional), you:
1. Call check_risk_limits — this is the code-level backstop. You MUST respect whatever it returns.
2. Consider current portfolio exposure (get_positions) and recent PnL.
3. Return a sizing decision: approved notional, stop-loss price, and take-profit price.

You do not override the code-level limits. If check_risk_limits rejects, your decision is reject with the reason.

Output format: the FINAL message MUST be a single JSON object (no prose, no code fences) matching:
{ "approved": boolean, "sizeQuote": number, "stopPrice": number|null, "takeProfitPrice": number|null, "reason": string }`;

const STRATEGY_SYSTEM = `You are the Strategy agent.

A candidate signal has been generated by deterministic code (EMA crossover, RSI reversion, breakout). Your job is qualitative judgment: does this signal make sense given broader market context right now?

Process:
1. Read the candidate features.
2. Pull recent klines and indicators (get_klines, get_indicators).
3. Consider: is the broader trend aligned? Is volatility reasonable? Are we fading a clear move for a weak reason?

Output format: the FINAL message MUST be a single JSON object (no prose, no code fences) matching:
{ "takeIt": boolean, "confidence": number, "reasoning": string }

Bias toward skipping marginal signals. A skipped candidate costs nothing; a bad fill costs real money.`;

const EXECUTION_SYSTEM = `You are the Execution agent.

You receive an approved trade (symbol, side, risk-approved size, stop, take-profit, candidate id). Risk and Strategy have already approved — you do not re-litigate.

Place the order with the RISK-APPROVED size exactly. Use type 'market' for urgent entries or 'limit' with a small offset for non-urgent. Attach stop via 'stop_market' if needed. Pass candidateId in the call.

Output format: the FINAL message MUST be a single JSON object (no prose, no code fences) matching:
{ "orderId": string, "type": string, "status": string, "avgFillPrice": number|null, "note": string }`;

const TOOL_SCHEMAS: Record<string, Anthropic.Tool> = {
  get_portfolio_summary: {
    name: "get_portfolio_summary",
    description: "Return current equity, open positions, daily PnL, and loop status.",
    input_schema: { type: "object", properties: {}, required: [] },
  },
  get_positions: {
    name: "get_positions",
    description: "List currently open positions.",
    input_schema: { type: "object", properties: {}, required: [] },
  },
  get_ticker: {
    name: "get_ticker",
    description: "Get last/bid/ask for a symbol.",
    input_schema: {
      type: "object",
      properties: { symbol: { type: "string" } },
      required: ["symbol"],
    },
  },
  get_klines: {
    name: "get_klines",
    description: "Fetch recent OHLCV candles.",
    input_schema: {
      type: "object",
      properties: {
        symbol: { type: "string" },
        timeframe: { type: "string", enum: ["1m", "5m", "15m", "1h", "4h", "1d"] },
        limit: { type: "integer", minimum: 10, maximum: 500 },
      },
      required: ["symbol", "timeframe"],
    },
  },
  get_indicators: {
    name: "get_indicators",
    description: "Compute EMA9/EMA21/EMA50/RSI14/ATR14/lastClose for a symbol+timeframe.",
    input_schema: {
      type: "object",
      properties: {
        symbol: { type: "string" },
        timeframe: { type: "string", enum: ["1m", "5m", "15m", "1h"] },
      },
      required: ["symbol", "timeframe"],
    },
  },
  check_risk_limits: {
    name: "check_risk_limits",
    description: "Code-level risk check. Returns approved size + stop + take-profit, or rejection.",
    input_schema: {
      type: "object",
      properties: {
        symbol: { type: "string" },
        side: { type: "string", enum: ["buy", "sell"] },
        desiredNotionalQuote: { type: "number" },
      },
      required: ["symbol", "side", "desiredNotionalQuote"],
    },
  },
  place_order: {
    name: "place_order",
    description: "Place an order. In dry-run, returns a simulated filled order.",
    input_schema: {
      type: "object",
      properties: {
        symbol: { type: "string" },
        side: { type: "string", enum: ["buy", "sell"] },
        type: { type: "string", enum: ["market", "limit", "stop_market", "stop_limit"] },
        amount: { type: "number" },
        price: { type: "number" },
        stopPrice: { type: "number" },
        candidateId: { type: "string" },
      },
      required: ["symbol", "side", "type", "amount", "candidateId"],
    },
  },
  cancel_order: {
    name: "cancel_order",
    description: "Cancel an open order.",
    input_schema: {
      type: "object",
      properties: {
        orderId: { type: "string" },
        symbol: { type: "string" },
      },
      required: ["orderId", "symbol"],
    },
  },
};

const RISK_TOOLS: Anthropic.Tool[] = [
  TOOL_SCHEMAS.check_risk_limits!,
  TOOL_SCHEMAS.get_positions!,
  TOOL_SCHEMAS.get_portfolio_summary!,
  TOOL_SCHEMAS.get_ticker!,
];

const STRATEGY_TOOLS: Anthropic.Tool[] = [
  TOOL_SCHEMAS.get_klines!,
  TOOL_SCHEMAS.get_indicators!,
  TOOL_SCHEMAS.get_ticker!,
];

const EXECUTION_TOOLS: Anthropic.Tool[] = [
  TOOL_SCHEMAS.place_order!,
  TOOL_SCHEMAS.cancel_order!,
  TOOL_SCHEMAS.get_ticker!,
];

export interface SubAgentDeps {
  client: Anthropic;
  ops: Ops;
  model: string;
  logger: Logger;
}

export class SubAgents {
  constructor(private deps: SubAgentDeps) {}

  delegateToRisk(task: string, context?: Record<string, unknown>): Promise<string> {
    return this.run({ system: RISK_SYSTEM, tools: RISK_TOOLS, role: "risk" }, task, context);
  }

  delegateToStrategy(task: string, context?: Record<string, unknown>): Promise<string> {
    return this.run(
      { system: STRATEGY_SYSTEM, tools: STRATEGY_TOOLS, role: "strategy" },
      task,
      context,
    );
  }

  delegateToExecution(task: string, context?: Record<string, unknown>): Promise<string> {
    return this.run(
      { system: EXECUTION_SYSTEM, tools: EXECUTION_TOOLS, role: "execution" },
      task,
      context,
    );
  }

  private async run(
    def: { system: string; tools: Anthropic.Tool[]; role: string },
    task: string,
    context: Record<string, unknown> | undefined,
  ): Promise<string> {
    const userText = context ? `${task}\n\nContext:\n${JSON.stringify(context, null, 2)}` : task;
    const history: Anthropic.MessageParam[] = [{ role: "user", content: userText }];

    for (let turn = 0; turn < 8; turn++) {
      const res = await this.deps.client.messages.create({
        model: this.deps.model,
        max_tokens: 2048,
        system: def.system,
        tools: def.tools,
        messages: history,
      });

      history.push({ role: "assistant", content: res.content });

      const toolUses = res.content.filter(
        (b): b is Anthropic.ToolUseBlock => b.type === "tool_use",
      );
      if (res.stop_reason !== "tool_use" || toolUses.length === 0) {
        const text = res.content
          .filter((b): b is Anthropic.TextBlock => b.type === "text")
          .map((b) => b.text)
          .join("\n")
          .trim();
        return text;
      }

      const results = await Promise.all(
        toolUses.map(async (t) => {
          const result = await this.executeTool(t.name, t.input as Record<string, unknown>);
          return {
            type: "tool_result" as const,
            tool_use_id: t.id,
            content: JSON.stringify(result),
          };
        }),
      );
      history.push({ role: "user", content: results });
    }
    this.deps.logger.warn("sub-agent hit turn limit", { role: def.role });
    return JSON.stringify({ error: "sub-agent exceeded turn limit" });
  }

  private async executeTool(name: string, input: Record<string, unknown>): Promise<unknown> {
    const o = this.deps.ops;
    switch (name) {
      case "get_portfolio_summary": return o.getPortfolioSummary();
      case "get_positions": return o.getPositions();
      case "get_ticker": return o.getTicker(input.symbol as string);
      case "get_klines":
        return o.getKlines(input.symbol as string, input.timeframe as string, input.limit as number | undefined);
      case "get_indicators":
        return o.getIndicators(input.symbol as string, input.timeframe as string);
      case "check_risk_limits":
        return o.checkRiskLimits(
          input.symbol as string,
          input.side as "buy" | "sell",
          input.desiredNotionalQuote as number,
        );
      case "place_order":
        return o.placeOrder(input as unknown as Parameters<Ops["placeOrder"]>[0]);
      case "cancel_order":
        return o.cancelOrder(input.orderId as string, input.symbol as string);
      default:
        return { error: `unknown tool: ${name}` };
    }
  }
}
