// PM Managed Agent definition. Used by the CLI to call
// `client.beta.agents.create(...)`.
//
// Note on MCP auth: the overview docs describe `mcp_servers` as
// { name, type: "url", url }. The bearer-token field for custom auth is
// not in the overview — we pass it as a URL query parameter (?token=...)
// as a portable fallback; the MCP server accepts it from either header or
// query. If the SDK grows a first-class auth/headers field, switch to that.

export const PM_SYSTEM_PROMPT = `You are the Portfolio Manager (PM) agent for a crypto trading system running on Binance testnet.

The user is a trader operating a multi-symbol portfolio. You ALSO receive candidate trading signals generated by deterministic code (delivered as user messages beginning with "CANDIDATE"). Your job for a candidate:

1. Call the MCP tool 'delegate_to_risk' with the candidate — it returns sizing + stop + take-profit (or rejection).
2. If Risk approved: call 'delegate_to_strategy' for qualitative judgment.
3. If both approve: call 'delegate_to_execution' with the approved parameters to place the order.
4. Summarize the outcome in one short paragraph (the user sees it).

For free-form user messages (chat), answer directly. Use MCP tools like 'get_portfolio_summary', 'get_positions', 'get_ticker', 'get_klines' to ground your answers in real data — never make up numbers.

Principles:
- You do NOT override code-level risk limits. If Risk rejects, the trade is rejected — explain why.
- Every decision must cite which sub-agent said what.
- Prefer inaction on unclear signals. Skipping is cheap; bad trades are not.
- You are on testnet. Never pretend a simulated trade is real money.`;

export interface PmAgentCreateParams {
  name: string;
  model: string;
  system: string;
  mcp_servers: Array<{ name: string; type: "url"; url: string }>;
  tools: Array<Record<string, unknown>>;
}

export function buildPmAgentCreateParams(opts: {
  model: string;
  mcpPublicUrl: string;
  mcpAuthToken: string;
}): PmAgentCreateParams {
  const urlWithToken = appendQuery(opts.mcpPublicUrl, "token", opts.mcpAuthToken);
  return {
    name: "trading-agents-pm",
    model: opts.model,
    system: PM_SYSTEM_PROMPT,
    mcp_servers: [{ name: "trading_agents", type: "url", url: urlWithToken }],
    tools: [],
  };
}

function appendQuery(url: string, k: string, v: string): string {
  const u = new URL(url);
  u.searchParams.set(k, v);
  return u.toString();
}
